### PR TITLE
Fix cython module

### PR DESCRIPTION
**Pull request by Luni-4**
We need to bump `0.7.2`

### CODE REVIEW

**Comment by rr-** [comment]
Also, could I ask you to push the releases and tag them in the library repositories other than bubblesub? (I still would like to see things before we push them, though)

**Comment by Luni-4** [comment]
> May I ask what's this doing? I mean, why is the library working without this

This code is taken from the original repository, it allows you to make use of the source code without having to install `cython`.

**Comment by Luni-4** [comment]
> Also, could I ask you to push the releases and tag them in the library repositories other than bubblesub? (I still would like to see things before we push them, though)

Sorry, I don't understand what you are referring to

**Comment by rr-** [comment]
So like for pympv2, pyffms2, pyass I'd like to be able to review the code, but once it gets approved, you wouldn't have to wait for me with merge and tagging and could do it yourself. Would that work for you?

**Comment by Luni-4** [comment]
Oh, sure, I can release it myself once a PR is approved

**Pull request merged**
